In [1]:
# from google.colab import drive

In [2]:
# drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# !cp -r drive/MyDrive/Test/SKT/gym_examples /content

In [1]:
!pip install gymnasium

   ---------------------------------------- 0.0/953.9 kB ? eta -:--:--
   - -------------------------------------- 30.7/953.9 kB 1.4 MB/s eta 0:00:01
   ------------------------ --------------- 593.9/953.9 kB 9.4 MB/s eta 0:00:01
   --------------------------------------- 953.9/953.9 kB 12.1 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import gymnasium as gym
env = gym.make('gym_examples:gym_examples/Reversi-v0', render_mode='text')

In [3]:
obs, info = env.reset()

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gymnasium\utils\passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be uint8, actual type: int16
  logger.warn(
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gymnasium\utils\passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")


In [4]:
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . . . . . . .
1 | . . . . . . . .
2 | . . . . . . . .
3 | . . . 1 2 . . .
4 | . . . 2 1 . . .
5 | . . . . . . . .
6 | . . . . . . . .
7 | . . . . . . . .
<class 'str'>


In [5]:
info['action_mask']

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [10]:
obs, reward, done,_, info = env.step((5, 3))

In [11]:
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . . . . . . .
1 | . . . . . . . .
2 | . . . . 1 . . .
3 | . . . 1 1 . . .
4 | . . . 1 2 2 . .
5 | . . . 2 . . . .
6 | . . 2 . . . . .
7 | . . . . . . . .
<class 'str'>


In [12]:
info['action_mask']

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [12]:
obs, reward, done, _,info = env.step((2, 2))

In [ ]:
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . . . . . . .
1 | . . . 2 . . . .
2 | . . 1 2 1 . . .
3 | . . . 2 1 . . .
4 | . . . 2 1 . . .
5 | . . . . . . . .
6 | . . . . . . . .
7 | . . . . . . . .
player: 2 opponent: 1
<class 'str'>


In [13]:
info['action_mask']

array([[0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [14]:
obs, reward, done,_, info = env.step((0, 2))
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . 1 . . . . .
1 | . . . 1 . . . .
2 | . . 1 2 2 2 . .
3 | . . . 2 2 . . .
4 | . . . 2 1 . . .
5 | . . . . . . . .
6 | . . . . . . . .
7 | . . . . . . . .
<class 'str'>


In [15]:
reward

-1